export const PRICE_CARD_DATA = [
    {
        id: 0,
        title: "Free Trail",
        currency: "$",
        price: "00",
        period: "per month",
        options: [
            "30 Free Trail",
            "5 Free Projects",
            "PHP 5 Enabled",
            "24/7 Suports",
        ],
        label: "ORDER NOW",
        buttonStyle: "btnCardServicePassive",
    },
    {
        id: 1,
        title: "Basic",
        currency: "$",
        price: "50",
        period: "per month",
        options: [
            "30 Free Trail",
            "5 Free Projects",
            "PHP 5 Enabled",
            "24/7 Suports",
        ],
        label: "ORDER NOW",
        buttonStyle: "btnCardServicePassive",
    },
    {
        id: 2,
        title: "Ultimates",
        currency: "$",
        price: "99",
        period: "per month",
        options: [
            "30 Free Trail",
            "5 Free Projects",
            "PHP 5 Enabled",
            "24/7 Suports",
        ],
        label: "ORDER NOW",
        buttonStyle: "btnCardServicePassive",
    },
]
